name: k6

on:
  # 手動実行
  workflow_dispatch:

jobs:
  k6test:
    name: Run k6 test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: k6 Load Test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: k6/workload.js
          flags: --vus 100000000 --duration 60s
